Default user roles
collective/pas.plugins.ldap pull request #112
Opened 2021-11-16 14:55 UTC by sauzher

This is the LDAPUserFolder _Default User Role_ feature implementation in pas.plugin.ldap

It adds another multi line input field in the controlpanel so that the administrator can give specific roles to users logged in through that pas plugin.

![immagine](https://user-images.githubusercontent.com/853815/142007318-d7b132e8-dcd7-44ad-84e7-15c07d812940.png)

alessandro.

2022-04-28 14:56 UTC, cekk commented
Any news about this pr? Could be nice to have it merged 😬

2022-04-29 11:04 UTC, jensens commented on src/pas/plugins/ldap/plugin.py
> +            return tuple(set(self._ldap_props.roles + ['Member']))
And I think we need an upgrade step to not break existing installation, right?

2022-04-29 16:30 UTC, sauzher commented on src/pas/plugins/ldap/plugin.py
> +            return tuple(set(self._ldap_props.roles + ['Member']))
> As we have a configuration for this now, can we have the Member role in the configuration too?

@jensens What configuration?
Do you mean using `Member` in place of `Anonymous`? here?
https://github.com/collective/pas.plugins.ldap/blob/2b5ece9be64b5c79b5d90b1946ca0aab00236f20/src/pas/plugins/ldap/plonecontrolpanel/profiles/base/ldapsettings.xml#L45

2022-04-30 10:01 UTC, jensens commented on src/pas/plugins/ldap/plugin.py
> +            return tuple(set(self._ldap_props.roles + ['Member']))
Member is added hard coded. I would expect it to be in the configuration as well. Anonymous is usually not what you want for a logged in user, its Authenticated (AFAIK it is anyway set) and most of the time Member.

2025-01-29 22:55 UTC, mamico requested changes

2025-01-29 22:55 UTC, mamico commented on src/pas/plugins/ldap/plonecontrolpanel/profiles/base/ldapsettings.xml
> +   <element type="string">Anonymous</element>
```suggestion
   <element type="string">Member</element>
```

2025-01-29 22:55 UTC, mamico commented on src/pas/plugins/ldap/plugin.py
> +            return tuple(set(self._ldap_props.roles + ['Member']))
```suggestion
            return tuple(set(self._ldap_props.roles))
```

2025-01-29 22:55 UTC, mamico commented on src/pas/plugins/ldap/properties.py
> +                # build attrmap from static keys and dynamic keys inputs
```suggestion
            # build attrmap from static keys and dynamic keys inputs
```

2025-01-30 07:03 UTC, sauzher commented
@mamico thanks!

2025-02-03 11:09 UTC, merged